# Generated by Django 4.2.7 on 2024-05-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Done',
            field=models.BooleanField(default=False),
        ),
    ]
