# Generated by Django 4.2.7 on 2024-05-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_todo_done"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="Done",
            new_name="done",
        ),
        migrations.AddField(
            model_name="todo",
            name="time_to_finish",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="time_to_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
