# Generated by Django 4.2.7 on 2024-05-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_rename_done_todo_done_todo_time_to_finish_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
